language: node_js
node_js:
  - node

cache: yarn

script:
  - ./bin/run --version
  - ./bin/run --help
  - yarn run test


after_success:
  - ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
  - bash < (curl -s https://codecov.io/bash)
